### ISSUE TITLE
V1.1.0 for Fabric 1.18.2 only Mining affecting intensity.

### ISSUE THREAD

**Issue by Jcraft153** [Fyustorm/mInetiface#10]
Using a Lovense Hush, only Mining is changing the intensity, Masochist, Experiance and Attack all not doing anything.  Tried toggling on and off these and tried restarting client.

**Comment by Fyustorm** [comment]
Hey, are you playing single player or multiplayer? 
V1.1.0 for 1.18.2 ? Where did you find this version ?

**Comment by Jcraft153** [comment]
Ah apologies, typo on my end, V1.1.0 for fabric 1.19.2.  Got it from 'How to install' link section on your github readme

Multiplayer, jar file only on clientside but I have access to server so if it needs to be serverside I can do that.

**Comment by Fyustorm** [comment]
Ok just wanted to be sure we were talking the same version :)
Problem is I only tested the mod on a Singleplayer at first because I didn't know it was different while playing on a server. I will need to check how to adapt events to work with multiplayer. For now I only tested to make it compatible for the Forge version (https://github.com/Fyustorm/mInetiface/issues/3)
I will try to see what I can do this weekend

**Comment by Fyustorm** [comment]
New fabric version that should work on multiplayer.
I tested mining, getting xp, getting hurt and attack
https://github.com/Fyustorm/mInetiface/releases/tag/v1.19.2-2.1.0

**Comment by Jcraft153** [comment]
Perfect, thanks!

**Comment by Jcraft153** [comment]
Working fine now, thanks!
