### ISSUE TITLE
forge

### ISSUE THREAD

**Issue by Moxie15** [Fyustorm/mInetiface#3]
forge plz?
and does 1.19.2 work?

**Comment by Fyustorm** [comment]
I did not plan to add forge support for now. I don't know if it's possible to use and maintain the same codebase to work with Fabric and Forge. If it's possible I will check what I can do in the next weeks but I can't guarantee anything.
You can still test the mod with Fabric on version 1.19.2 here : https://github.com/Fyustorm/mInetiface/releases/tag/v1.19.2-1.1.0

**Comment by Moxie15** [comment]
Alright

**Comment by Fyustorm** [comment]
I did check and it's possible. I will try my best to do it in 2 weeks but no promise

**Comment by Fyustorm** [comment]
Hey you can check the new release here : https://github.com/Fyustorm/mInetiface/releases/tag/v1.19.2-2.0.0
I removed the config menu from the mod but you can still tweak it as you like directly by editing the config file. I updated the [README](https://github.com/Fyustorm/mInetiface/) for more informations.

Please let me know if it's working or not

**Comment by Moxie15** [comment]
Thx
I'll try when I get home after work

**Comment by Moxie15** [comment]
it works very nice

**Comment by Moxie15** [comment]
but how do i strart it on it when im on a server

**Comment by Fyustorm** [comment]
Hey I did not tried it on server before. 
After testing it, it seems like it can't work as is on a server.
Some events that I am using are registered on the server side (so it's working on singleplayer because the game is running the client and the server side on local).
So to make it work on a server I will need to find alternative for theses events : 
PlayerXpEvent.XpChange --> ???
BlockEvent.BreakEvent --> PlayerEvent.HarvestCheck not exactly the same but it could do it
LivingDamageEvent --> CriticalHitEvent
LivingHurtEvent --> ???
LivingDeathEvent --> ???

**Comment by Fyustorm** [comment]
You can check the first release that is working while playing on a server [https://github.com/Fyustorm/mInetiface/releases/tag/v1.19.2-2.1.0](https://github.com/Fyustorm/mInetiface/releases/tag/v1.19.2-2.1.0)

I removed events based on hurt, death and xp.

Event for mining has changed compared to the server side event I was using before. So you should remove your **minetiface.config** from your **config** folder because I totally changed default block scores. This is a first try to make the new event work for mining so send me your feedback because it might need some tweaks !

**Comment by Moxie15** [comment]
you could make a plugin so ppl with the toys can join and it works for eveyone but the problem is the owner
and sorry for talking to you sooner i was going tho a ruff spot 
and i have a server that we can try it on but i thing we should get in better communication method like discord

**Comment by Fyustorm** [comment]
I'm not sure to understand exactly what you want to achieve. If the server is installed on the server how would you use multiple Intiface client to react to each player ?
You can always add me to discord if you want (fyustorm) but I'm never online, and we are likely not on the same timezone (Paris for me)
